### ISSUE TITLE
Lock unlock not working?

### ISSUE THREAD

**Issue by kevinVl** [Tobiaswk/dartnissanconnect#7]
I'm trying to call the Lock Unlock function but I'm getting  a 
{"errors":[{"status":"Bad Request","code":"400","title":"Http message is not readable"}]} response back 

body : 
{"type":"LockUnlock","attributes":{"lock":"lock","doortype":"doors_hatch","srp":""}}

Anything I'm missing here? fyi this is for the new Ariya model.

**Comment by Tobiaswk** [comment]
Hello,

Lock/Unlock is really not supported as it requires what is called an srp token to function. I haven't figured out how it works and I don't think anyone else has.

Currently there is an skeleton implementation which obviously needs a real implementation.

Sorry to disappoint!

**Comment by jumpjack** [comment]
Did anybody try with **"action" : "lock"** rather than **"lock" : "lock"**?
And any news about SRP authentication?

**Comment by Tobiaswk** [comment]
The SRP authentication is not implemented as I or others haven't reverse engineered that part of the API.
-------- Oprindelig besked --------Fra: jumpjack ***@***.***> Dato: 16.10.2023  11.32  (GMT+01:00) Til: Tobiaswk/dartnissanconnect ***@***.***> Cc: Tobias Westergaard Kjeldsen ***@***.***>, State change ***@***.***> Emne: Re: [Tobiaswk/dartnissanconnect] Lock unlock not working? (Issue #7) 
Did anybody try with "action" : "lock" rather than "lock" : "lock"?
And any news about SRP authentication?
